; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
name = LumenLab
description = "An LED strip gaming and entertainment platform that turns any space into an interactive playground of abstract retro games and animations powered by an ESP32"
default_envs = debug

[env]
upload_speed = 921600
monitor_speed = 921600

[env:virtualization]
platform = espressif32
board = upesy_wroom
framework = arduino
build_type = debug
build_unflags = -std=gnu++11
build_flags = -g -DVIRTUALIZATION -std=gnu++2a
lib_deps = 
	fastled/FastLED@^3.10.2
	adafruit/Adafruit SSD1306@^2.5.15
	adafruit/Adafruit GFX Library@^1.12.1
	pablomarquez76/PS4_Controller_Host@^1.1.1

[env:virtualization_ps3]
platform = espressif32
board = upesy_wroom
framework = arduino
build_type = debug
build_unflags = -std=gnu++11
build_flags = -g -DVIRTUALIZATION -DUSE_PS3 -std=gnu++2a
lib_deps = 
	jvpernis/PS3 Controller Host@^1.1.0
	fastled/FastLED@^3.10.2
	adafruit/Adafruit SSD1306@^2.5.15
	adafruit/Adafruit GFX Library@^1.12.1

[env:debug]
platform = espressif32
board = upesy_wroom
framework = arduino
build_type = debug
build_unflags = -std=gnu++11
build_flags = -g -DDEBUG -std=gnu++2a
lib_deps = 
	fastled/FastLED@^3.10.2
	adafruit/Adafruit SSD1306@^2.5.15
	adafruit/Adafruit GFX Library@^1.12.1
	pablomarquez76/PS4_Controller_Host@^1.1.1

[env:release]
platform = espressif32
board = upesy_wroom
framework = arduino
build_type = release
build_unflags = -std=gnu++11
build_flags =
	-Os
	-DRELEASE
	-std=gnu++2a
	-DLUMENLAB_VERSION=\"${sysenv.LUMENLAB_VERSION}\"
	lib_deps = 
	fastled/FastLED@^3.10.2
	adafruit/Adafruit SSD1306@^2.5.15
	adafruit/Adafruit GFX Library@^1.12.1
	pablomarquez76/PS4_Controller_Host@^1.1.1

[env:native]
platform = native
test_framework = googletest
build_unflags = -std=gnu++11
build_flags = 
	-I.pio/libdeps/native/googletest/googletest/include/gtest
	-I.pio/libdeps/native/googletest/googlemock/include/gmock
	-pthread
	-std=gnu++2a
lib_deps = 
	fastled/FastLED@^3.10.2
	adafruit/Adafruit SSD1306@^2.5.15
	adafruit/Adafruit GFX Library@^1.12.1
	pablomarquez76/PS4_Controller_Host@^1.1.1

####
# To explore later: ESP-Prog debugging
####
; debug_tool = esp-prog
; upload_protocol = esp-prog
; debug_init_break = tbreak setup
; debug_extra_cmds =
;   set remote hardware-breakpoint-limit 2
;   set remote hardware-watchpoint-limit 1
; debug_speed = 1000